export const mockDockingJobs = [
  {
    job_id: "job_001_aspirin_cox2",
    status: "completed" as const,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    protein_name: "COX-2 Enzyme",
    ligand_name: "Aspirin",
  },
  {
    job_id: "job_002_ibuprofen_cox1",
    status: "completed" as const,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    protein_name: "COX-1 Enzyme",
    ligand_name: "Ibuprofen",
  },
  {
    job_id: "job_003_remdesivir_rdrp",
    status: "running" as const,
    created_at: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    protein_name: "RNA-dependent RNA polymerase",
    ligand_name: "Remdesivir",
    progress: 65,
  },
  {
    job_id: "job_004_penicillin_pbp",
    status: "queued" as const,
    created_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    protein_name: "Penicillin-binding protein",
    ligand_name: "Penicillin G",
  },
  {
    job_id: "job_005_statin_hmgr",
    status: "failed" as const,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    protein_name: "HMG-CoA reductase",
    ligand_name: "Atorvastatin",
    error: "Invalid protein structure format",
  },
]

const EXAMPLE_PDB = `COMPND    UNNAMED
AUTHOR    GENERATED BY OPEN BABEL 2.3.2
ATOM      1  N   ALA A   1       0.000   0.000   0.000  1.00  0.00           N  
ATOM      2  CA  ALA A   1       1.456   0.000   0.000  1.00  0.00           C  
ATOM      3  C   ALA A   1       1.930   0.000   1.463  1.00  0.00           C  
ATOM      4  O   ALA A   1       1.160   0.000   2.421  1.00  0.00           O  
ATOM      5  HN  ALA A   1      -0.495   0.091   0.883  1.00  0.00           H  
ATOM      6  HA  ALA A   1       1.799  -0.926  -0.476  1.00  0.00           H  
ATOM      7  CB  ALA A   1       2.010   1.208  -0.746  1.00  0.00           C  
ATOM      8  1HB ALA A   1       1.657   1.230  -1.782  1.00  0.00           H  
ATOM      9  2HB ALA A   1       1.695   2.143  -0.268  1.00  0.00           H  
ATOM     10  3HB ALA A   1       3.104   1.197  -0.763  1.00  0.00           H  
ATOM     11  HN  ALA A   1      -0.508   0.077  -0.877  1.00  0.00           H  
ATOM     12  N   ALA A   2       3.241  -0.000   1.742  1.00  0.00           N  
ATOM     13  CA  ALA A   2       3.690   0.000   3.127  1.00  0.00           C  
ATOM     14  C   ALA A   2       5.228   0.000   3.127  1.00  0.00           C  
ATOM     15  O   ALA A   2       5.902  -0.000   2.098  1.00  0.00           O  
ATOM     16  HN  ALA A   2       3.928  -0.091   0.999  1.00  0.00           H  
ATOM     17  HA  ALA A   2       3.343   0.926   3.600  1.00  0.00           H  
ATOM     18  CB  ALA A   2       3.151  -1.208   3.884  1.00  0.00           C  
ATOM     19  1HB ALA A   2       2.057  -1.230   3.869  1.00  0.00           H  
ATOM     20  2HB ALA A   2       3.508  -2.143   3.438  1.00  0.00           H  
ATOM     21  3HB ALA A   2       3.472  -1.197   4.931  1.00  0.00           H  
ATOM     22  N   ALA A   3       5.898   0.000   4.287  1.00  0.00           N  
ATOM     23  CA  ALA A   3       7.353   0.000   4.287  1.00  0.00           C  
ATOM     24  C   ALA A   3       7.828   0.000   5.750  1.00  0.00           C  
ATOM     25  O   ALA A   3       7.058   0.001   6.709  1.00  0.00           O  
ATOM     26  HN  ALA A   3       5.403   0.092   5.170  1.00  0.00           H  
ATOM     27  HA  ALA A   3       7.696  -0.926   3.811  1.00  0.00           H  
ATOM     28  CB  ALA A   3       7.907   1.208   3.541  1.00  0.00           C  
ATOM     29  1HB ALA A   3       7.555   1.230   2.505  1.00  0.00           H  
ATOM     30  2HB ALA A   3       7.593   2.143   4.018  1.00  0.00           H  
ATOM     31  3HB ALA A   3       9.002   1.197   3.524  1.00  0.00           H  
ATOM     32  N   ALA A   4       9.138   0.000   6.029  1.00  0.00           N  
ATOM     33  CA  ALA A   4       9.587   0.001   7.414  1.00  0.00           C  
ATOM     34  C   ALA A   4      11.125   0.000   7.414  1.00  0.00           C  
ATOM     35  O   ALA A   4      11.799  -0.000   6.386  1.00  0.00           O  
ATOM     36  HN  ALA A   4       9.825  -0.092   5.286  1.00  0.00           H  
ATOM     37  HA  ALA A   4       9.240   0.927   7.887  1.00  0.00           H  
ATOM     38  CB  ALA A   4       9.048  -1.207   8.171  1.00  0.00           C  
ATOM     39  1HB ALA A   4       7.954  -1.229   8.156  1.00  0.00           H  
ATOM     40  2HB ALA A   4       9.405  -2.142   7.726  1.00  0.00           H  
ATOM     41  3HB ALA A   4       9.370  -1.196   9.218  1.00  0.00           H  
ATOM     42  N   PHE A   5      11.795   0.001   8.574  1.00  0.00           N  
ATOM     43  CA  PHE A   5      13.257   0.000   8.574  1.00  0.00           C  
ATOM     44  C   PHE A   5      13.697   0.001  10.048  1.00  0.00           C  
ATOM     45  O   PHE A   5      12.900   0.002  10.985  1.00  0.00           O  
ATOM     46  CB  PHE A   5      13.815   1.225   7.831  1.00  0.00           C  
ATOM     47  CG  PHE A   5      15.237   1.036   7.355  1.00  0.00           C  
ATOM     48  CD2 PHE A   5      16.308   1.641   8.027  1.00  0.00           C  
ATOM     49  CE2 PHE A   5      17.618   1.438   7.592  1.00  0.00           C  
ATOM     50  CZ  PHE A   5      17.869   0.639   6.477  1.00  0.00           C  
ATOM     51  CE1 PHE A   5      16.810   0.041   5.797  1.00  0.00           C  
ATOM     52  CD1 PHE A   5      15.500   0.236   6.234  1.00  0.00           C  
ATOM     53  H   PHE A   5      11.328   0.281   9.433  1.00  0.00           H  
ATOM     54  HA  PHE A   5      13.585  -0.939   8.112  1.00  0.00           H  
ATOM     55  HB1 PHE A   5      13.752   2.118   8.467  1.00  0.00           H  
ATOM     56  HB2 PHE A   5      13.201   1.454   6.950  1.00  0.00           H  
ATOM     57  HD2 PHE A   5      16.130   2.272   8.895  1.00  0.00           H  
ATOM     58  HE2 PHE A   5      18.445   1.910   8.117  1.00  0.00           H  
ATOM     59  HZ  PHE A   5      18.889   0.489   6.133  1.00  0.00           H  
ATOM     60  HE1 PHE A   5      17.003  -0.573   4.921  1.00  0.00           H  
ATOM     61  HD1 PHE A   5      14.680  -0.233   5.690  1.00  0.00           H  
ATOM     62  N   ALA A   6      15.001   0.000  10.358  1.00  0.00           N  
ATOM     63  CA  ALA A   6      15.418   0.001  11.752  1.00  0.00           C  
ATOM     64  C   ALA A   6      16.955   0.001  11.788  1.00  0.00           C  
ATOM     65  O   ALA A   6      17.653  -0.000  10.776  1.00  0.00           O  
ATOM     66  HN  ALA A   6      15.705  -0.092   9.631  1.00  0.00           H  
ATOM     67  HA  ALA A   6      15.060   0.927  12.217  1.00  0.00           H  
ATOM     68  CB  ALA A   6      14.861  -1.206  12.497  1.00  0.00           C  
ATOM     69  1HB ALA A   6      13.767  -1.228  12.457  1.00  0.00           H  
ATOM     70  2HB ALA A   6      15.228  -2.142  12.060  1.00  0.00           H  
ATOM     71  3HB ALA A   6      15.158  -1.195  13.551  1.00  0.00           H  
ATOM     72  N   ALA A   7      17.598   0.001  12.964  1.00  0.00           N  
ATOM     73  CA  ALA A   7      19.053   0.000  12.998  1.00  0.00           C  
ATOM     74  C   ALA A   7      19.494   0.001  14.471  1.00  0.00           C  
ATOM     75  O   ALA A   7      18.701   0.002  15.412  1.00  0.00           O  
ATOM     76  HN  ALA A   7      17.083   0.093  13.835  1.00  0.00           H  
ATOM     77  HA  ALA A   7      19.407  -0.926  12.530  1.00  0.00           H  
ATOM     78  CB  ALA A   7      19.625   1.208  12.264  1.00  0.00           C  
ATOM     79  1HB ALA A   7      19.297   1.229  11.219  1.00  0.00           H  
ATOM     80  2HB ALA A   7      19.300   2.143  12.733  1.00  0.00           H  
ATOM     81  3HB ALA A   7      20.720   1.196  12.272  1.00  0.00           H  
ATOM     82  N   ALA A   8      20.797   0.001  14.781  1.00  0.00           N  
ATOM     83  CA  ALA A   8      21.214   0.002  16.175  1.00  0.00           C  
ATOM     84  C   ALA A   8      22.751   0.001  16.211  1.00  0.00           C  
ATOM     85  O   ALA A   8      23.449  -0.001  15.199  1.00  0.00           O  
ATOM     86  HN  ALA A   8      21.502  -0.092  14.054  1.00  0.00           H  
ATOM     87  HA  ALA A   8      20.857   0.928  16.640  1.00  0.00           H  
ATOM     88  CB  ALA A   8      20.657  -1.206  16.921  1.00  0.00           C  
ATOM     89  1HB ALA A   8      19.563  -1.227  16.880  1.00  0.00           H  
ATOM     90  2HB ALA A   8      21.024  -2.141  16.484  1.00  0.00           H  
ATOM     91  3HB ALA A   8      20.954  -1.194  17.975  1.00  0.00           H  
ATOM     92  N   ALA A   9      23.394   0.002  17.387  1.00  0.00           N  
ATOM     93  CA  ALA A   9      24.850   0.000  17.421  1.00  0.00           C  
ATOM     94  C   ALA A   9      25.290   0.002  18.894  1.00  0.00           C  
ATOM     95  O   ALA A   9      24.498   0.003  19.835  1.00  0.00           O  
ATOM     96  HN  ALA A   9      22.879   0.094  18.258  1.00  0.00           H  
ATOM     97  HA  ALA A   9      25.203  -0.926  16.953  1.00  0.00           H  
ATOM     98  CB  ALA A   9      25.421   1.208  16.687  1.00  0.00           C  
ATOM     99  1HB ALA A   9      25.093   1.229  15.642  1.00  0.00           H  
ATOM    100  2HB ALA A   9      25.097   2.143  17.156  1.00  0.00           H  
ATOM    101  3HB ALA A   9      26.517   1.196  16.695  1.00  0.00           H  
ATOM    102  OXT ALA A   9      26.620   0.001  19.131  1.00  0.00           O  
ATOM    103  HO  ALA A   9      27.305  -0.000  18.317  1.00  0.00           H  
CONECT    1   11    2    5                                            
CONECT    2    1    3    6    7                                       
CONECT    3    2    4   12                                            
CONECT    4    3                                                      
CONECT    5    1                                                      
CONECT    6    2                                                      
CONECT    7    2    8    9   10                                       
CONECT    8    7                                                      
CONECT    9    7                                                      
CONECT   10    7                                                      
CONECT   11    1                                                      
CONECT   12    3   13   16                                            
CONECT   13   12   14   17   18                                       
CONECT   14   13   15   22                                            
CONECT   15   14                                                      
CONECT   16   12                                                      
CONECT   17   13                                                      
CONECT   18   13   19   20   21                                       
CONECT   19   18                                                      
CONECT   20   18                                                      
CONECT   21   18                                                      
CONECT   22   14   23   26                                            
CONECT   23   22   24   27   28                                       
CONECT   24   23   25   32                                            
CONECT   25   24                                                      
CONECT   26   22                                                      
CONECT   27   23                                                      
CONECT   28   23   29   30   31                                       
CONECT   29   28                                                      
CONECT   30   28                                                      
CONECT   31   28                                                      
CONECT   32   24   33   36                                            
CONECT   33   32   34   37   38                                       
CONECT   34   33   35   42                                            
CONECT   35   34                                                      
CONECT   36   32                                                      
CONECT   37   33                                                      
CONECT   38   33   39   40   41                                       
CONECT   39   38                                                      
CONECT   40   38                                                      
CONECT   41   38                                                      
CONECT   42   34   43   53                                            
CONECT   43   42   44   46   54                                       
CONECT   44   43   45   62                                            
CONECT   45   44                                                      
CONECT   46   43   47   56   55                                       
CONECT   47   46   48   52                                            
CONECT   48   47   49   57                                            
CONECT   49   48   50   58                                            
CONECT   50   49   51   59                                            
CONECT   51   50   52   60                                            
CONECT   52   47   51   61                                            
CONECT   53   42                                                      
CONECT   54   43                                                      
CONECT   55   46                                                      
CONECT   56   46                                                      
CONECT   57   48                                                      
CONECT   58   49                                                      
CONECT   59   50                                                      
CONECT   60   51                                                      
CONECT   61   52                                                      
CONECT   62   44   63   66                                            
CONECT   63   62   64   67   68                                       
CONECT   64   63   65   72                                            
CONECT   65   64                                                      
CONECT   66   62                                                      
CONECT   67   63                                                      
CONECT   68   63   69   70   71                                       
CONECT   69   68                                                      
CONECT   70   68                                                      
CONECT   71   68                                                      
CONECT   72   64   73   76                                            
CONECT   73   72   74   77   78                                       
CONECT   74   73   75   82                                            
CONECT   75   74                                                      
CONECT   76   72                                                      
CONECT   77   73                                                      
CONECT   78   73   79   80   81                                       
CONECT   79   78                                                      
CONECT   80   78                                                      
CONECT   81   78                                                      
CONECT   82   74   83   86                                            
CONECT   83   82   84   87   88                                       
CONECT   84   83   85   92                                            
CONECT   85   84                                                      
CONECT   86   82                                                      
CONECT   87   83                                                      
CONECT   88   83   89   90   91                                       
CONECT   89   88                                                      
CONECT   90   88                                                      
CONECT   91   88                                                      
CONECT   92   84   93   96                                            
CONECT   93   92   94   97   98                                       
CONECT   94   93   95  102                                            
CONECT   95   94                                                      
CONECT   96   92                                                      
CONECT   97   93                                                      
CONECT   98   93   99  100  101                                       
CONECT   99   98                                                      
CONECT  100   98                                                      
CONECT  101   98                                                      
CONECT  102   94  103                                                 
CONECT  103  102                                                      
MASTER        0    0    0    0    0    0    0    0  103    0  103    0
END`

export const mockDockingResults = {
  job_001_aspirin_cox2: {
    job_id: "job_001_aspirin_cox2",
    protein_name: "COX-2 Enzyme",
    ligand_name: "Aspirin",
    best_pose: {
      pose_id: 0,
      score: -8.7,
      rmsd: 0.0,
      cluster_id: 1,
      pose_file: EXAMPLE_PDB,
    },
    poses: [
      {
        pose_id: 0,
        score: -8.7,
        rmsd: 0.0,
        cluster_id: 1,
        pose_file: EXAMPLE_PDB,
      },
      {
        pose_id: 1,
        score: -8.3,
        rmsd: 1.2,
        cluster_id: 1,
        pose_file: EXAMPLE_PDB,
      },
      {
        pose_id: 2,
        score: -7.9,
        rmsd: 2.1,
        cluster_id: 2,
        pose_file: EXAMPLE_PDB,
      },
      {
        pose_id: 3,
        score: -7.5,
        rmsd: 2.8,
        cluster_id: 2,
        pose_file: EXAMPLE_PDB,
      },
      {
        pose_id: 4,
        score: -7.2,
        rmsd: 3.4,
        cluster_id: 3,
        pose_file: EXAMPLE_PDB,
      },
      {
        pose_id: 5,
        score: -6.9,
        rmsd: 4.1,
        cluster_id: 3,
        pose_file: EXAMPLE_PDB,
      },
    ],
    metrics: {
      mean_score: -7.75,
      std_score: 0.67,
      best_rmsd: 0.0,
      confidence_score: 0.89,
    },
    execution_time: 342.5,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  job_002_ibuprofen_cox1: {
    job_id: "job_002_ibuprofen_cox1",
    protein_name: "COX-1 Enzyme",
    ligand_name: "Ibuprofen",
    best_pose: {
      pose_id: 0,
      score: -9.2,
      rmsd: 0.0,
      cluster_id: 1,
      pose_file: EXAMPLE_PDB,
    },
    poses: [
      {
        pose_id: 0,
        score: -9.2,
        rmsd: 0.0,
        cluster_id: 1,
        pose_file: EXAMPLE_PDB,
      },
      {
        pose_id: 1,
        score: -8.8,
        rmsd: 1.1,
        cluster_id: 1,
        pose_file: EXAMPLE_PDB,
      },
      {
        pose_id: 2,
        score: -8.4,
        rmsd: 1.9,
        cluster_id: 2,
        pose_file: EXAMPLE_PDB,
      },
      {
        pose_id: 3,
        score: -8.0,
        rmsd: 2.5,
        cluster_id: 2,
        pose_file: EXAMPLE_PDB,
      },
    ],
    metrics: {
      mean_score: -8.6,
      std_score: 0.49,
      best_rmsd: 0.0,
      confidence_score: 0.92,
    },
    execution_time: 289.3,
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
}

export const mockBlockchainTransactions = [
  {
    signature: "5J7Xz9YmK3P4vW8nQ2fR6tL1sA7hD9cG4eB3jF8mN6pX2vK5wT9yU4rE1oI7qH3sL6nM8bV4cZ2xW5tY1pR7aK9",
    jobId: "job_001_aspirin_cox2",
    reportType: "comprehensive",
    stakeholder: "researcher",
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    reportHash: "a7f3e9d2c8b4f1a6e5d3c9b7a2f8e4d1c6b9a5e2f7d3c8b4a1e6f9d2c5b8a3e7",
    metadata: {
      proteinName: "COX-2 Enzyme",
      ligandName: "Aspirin",
      bindingScore: -8.7,
      confidence: 0.89,
    },
    blockTime: Math.floor((Date.now() - 1 * 60 * 60 * 1000) / 1000),
    slot: 245678901,
  },
  {
    signature: "4K6Yw8XlJ2O3uV7mP1eQ5sK0rZ6hC8bF3dA2iE7lM5oW1uJ4vS8xT3qD0nH6pK2rL5mN7aU3bY1wS4oP6zJ8",
    jobId: "job_002_ibuprofen_cox1",
    reportType: "summary",
    stakeholder: "investor",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    reportHash: "b8g4f0e3d9c5g2b7f6e4d0c8b3a9f5e2d7c0b6a3f8e5d2c9b7a4f1e8d3c6b0a9",
    metadata: {
      proteinName: "COX-1 Enzyme",
      ligandName: "Ibuprofen",
      bindingScore: -9.2,
      confidence: 0.92,
    },
    blockTime: Math.floor((Date.now() - 3 * 60 * 60 * 1000) / 1000),
    slot: 245667812,
  },
]

export const mockAIAnalyses = {
  job_001_aspirin_cox2: {
    researcher: {
      summary:
        "The docking study reveals a strong binding interaction between Aspirin and COX-2 enzyme with a binding affinity of -8.7 kcal/mol, indicating high therapeutic potential.",
      bindingAnalysis: {
        score: -8.7,
        interpretation:
          "Excellent binding affinity suggesting strong inhibition of COX-2 activity. The negative value indicates favorable energetics.",
        keyInteractions: [
          "Hydrogen bond with Ser530 (2.1 Å)",
          "Pi-stacking interaction with Tyr385",
          "Hydrophobic contacts with Val523 and Ala527",
        ],
      },
      drugLikeness: {
        lipinski: { passed: true, violations: 0 },
        admet: {
          absorption: "High",
          distribution: "Good CNS penetration",
          metabolism: "CYP2C9 substrate",
          excretion: "Primarily renal",
          toxicity: "Low hepatotoxicity risk",
        },
      },
      recommendations: [
        "Consider structural modifications to enhance selectivity",
        "Investigate metabolite activity profiles",
        "Perform in vitro binding assays for validation",
      ],
      confidence: 0.89,
    },
    investor: {
      summary:
        "Strong commercial potential based on excellent binding characteristics and favorable drug-like properties. Market opportunity in pain management sector.",
      marketOpportunity:
        "The global NSAID market size was valued at $15.8B in 2023 with a CAGR of 4.2%. COX-2 selective inhibitors represent a growing segment.",
      competitiveLandscape: [
        "Celecoxib (Celebrex) - Market leader",
        "Etoricoxib (Arcoxia) - European market",
        "Parecoxib - Injectable formulation",
      ],
      developmentTimeline: "36-48 months to clinical trials, 8-10 years to market",
      estimatedCost: "$800M - $1.2B total development cost",
      riskFactors: [
        "Cardiovascular safety concerns for COX-2 inhibitors",
        "Patent landscape complexity",
        "Regulatory pathway for novel NSAID",
      ],
      confidence: 0.85,
    },
    regulator: {
      summary:
        "Preliminary computational evidence suggests acceptable safety profile. Requires comprehensive preclinical validation before human trials.",
      safetyProfile: {
        cardiovascular: "Moderate risk - requires monitoring",
        gastrointestinal: "Reduced risk vs non-selective NSAIDs",
        renal: "Standard NSAID precautions apply",
        hepatic: "Low concern based on structural analysis",
      },
      requiredStudies: [
        "Acute and chronic toxicity studies (GLP)",
        "Cardiovascular safety assessment",
        "Drug-drug interaction profiling",
        "Pharmacokinetic studies in multiple species",
        "Genotoxicity and carcinogenicity studies",
      ],
      regulatoryPathway: "NDA submission under 505(b)(1) - New Chemical Entity",
      complianceNotes: [
        "Follow ICH M3(R2) guidance for nonclinical safety studies",
        "Cardiovascular outcomes trial may be required",
        "Implement REMS program if approved",
      ],
      confidence: 0.87,
    },
    clinician: {
      summary:
        "Promising candidate for pain management with potentially improved gastrointestinal safety profile compared to traditional NSAIDs.",
      clinicalApplication: {
        indications: ["Acute pain management", "Chronic inflammatory conditions", "Postoperative analgesia"],
        dosing: "Recommended starting dose: 50-100mg BID based on modeling",
        administration: "Oral formulation preferred, IV option for acute settings",
      },
      patientPopulation: {
        ideal: "Adults with osteoarthritis, rheumatoid arthritis, or acute pain",
        contraindications: [
          "Known hypersensitivity to NSAIDs",
          "Recent cardiovascular event",
          "Severe renal impairment",
        ],
        monitoring: "Renal function, blood pressure, cardiovascular status",
      },
      adverseEffects: {
        common: ["Headache", "Dyspepsia", "Peripheral edema"],
        serious: ["Cardiovascular events", "Acute renal failure", "Severe hypersensitivity"],
      },
      recommendations: [
        "Start with lowest effective dose",
        "Monitor cardiovascular risk factors",
        "Consider gastroprotection in high-risk patients",
        "Regular renal function monitoring in elderly",
      ],
      confidence: 0.88,
    },
  },
}
